### ISSUE TITLE
Sources are case sensitive

### ISSUE THREAD

**Issue by LPGhatguy** [rojo-rbx/foreman#10]
These two tools should be the same, but currently aren't:

```toml
[tools]
rojo = { source = "ROJO-RBX/ROJO", version = "0.5.0" }
rojo2 = { source = "rojo-rbx/rojo", version = "0.5.0" }
```

It's probably safe to force sources to be lowercase. Alternatively, we could wrap them in a newtype wrapper whose `Hash` implementation transforms each character to be lowercase first.
