### ISSUE TITLE
Executable names are weird

### ISSUE THREAD

**Issue by LPGhatguy** [rojo-rbx/foreman#11]
If you install Rojo via Foreman...

```toml
[tools]
rojo = { source = "rojo-rbx/rojo", version = "0.6.0-alpha.1" }
```

and then run `rojo --help`, you'll see that Rojo knows that its executable name is weird:

![image](https://user-images.githubusercontent.com/654598/74370246-9e4f2000-4d8b-11ea-886e-7f6ebc7b7c0e.png)

Rustup solves this by keeping the executable names the same, but putting them into subfolders. We should adopt that strategy, too!
