### ISSUE TITLE
Support subprojects from repositories

### ISSUE THREAD

**Issue by LPGhatguy** [rojo-rbx/foreman#9]
Some projects don't have a tool as their primary project or might publish multiple tools from the same repository.

It would be useful to be able to declare dependencies on these, maybe like:

```toml
[tools]
genref = { source = "rojo-rbx/rbx-dom/generate-reflection", version = "1.2.6" }
```

We would probably need a special convention for tags to make this kind of detection feasible, like `generate-reflection-v1.2.6`. I've been following this in the rbx-dom repository and it seems to work fairly well.
